services:
  postgres:
    image: postgres:latest
    container_name: postgres_auth_service
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=authorization-db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
